import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/globals.scss";
import { AuthProvider } from "./authProvider";
import Footer from "@/components/organisms/footer/Footer";

const font = Raleway({
    variable: "--font-principal",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "MedMinder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={font.variable}>
                <AuthProvider>
                    {children}
                    <Footer/>
                </AuthProvider>
            </body>
        </html>
    );
}
